### PR TITLE
Handle correctly single action for createActionType

### LINKED ISSUE #12: createActionType requires at least 2 actions
It's a small thing, but made me wonder for a while. I am trying to setup things and had only single action there to see it working. Unfortunately that fails with `tcomb.union`

```
TypeError: [tcomb] Invalid argument types [
  "FIRST_ACTION"
] supplied to union(types, [name]) combinator (expected an array of at least 2 types)
```

I am not entirely sure yet why that union is there, but should be handled more properly I guess.

### PR DESCRIPTION
**Pull request by danielkcz**
Fixes #12

### CODE REVIEW

**Comment by danielkcz** [comment]
Actually I am bit confused about that `dispatch` now. Will it work like that?

**Comment by gcanti** [comment]
`dispatch` is useful only in presence of a union. I was thinking to something along the lines of

``` js
var t = require('tcomb');

function createUnion(types, dispatcher) {
  var Action = t.union(types, 'Action');
  Action.dispatch = function (x) {
    return dispatcher[x.type];
  };
  return Action
}

function createActionType(actions) {
  var dispatcher = {};
  var types = [];
  var actionCreators = {};
  Object.keys(actions).forEach(function (type) {
    types.push(dispatcher[type] = t.interface.extend([actions[type], { type: t.enums.of(type) }], type));
    actionCreators[type] = function (x) {
      return t.mixin({ type: type }, x);
    };
  });
  var Action = types.length === 1 ? types[0] : createUnion(types, dispatcher);
  Action.creators = actionCreators;
  t.mixin(Action, actionCreators);
  return Action;
}

module.exports = createActionType;
```

**Comment by danielkcz** [comment]
Hmm, I don't see much of difference except it doesn't add that `dispatch` there. Feel free to implement by yourself if you don't like this way.

**Comment by gcanti** [comment]
@FredyC you asked

> Will it work like that?

My responsibility was to answer

It's not _that_ important but there are some differences:
- as stated above, in the case of only one type the `dispatch` function is pointless
- no need to throw an error: the union combinator will complain if the input is wrong

**Comment by danielkcz** [comment]
The `dispatch` might be actually useful in case someone is using that directly for some reason. It's not good to change API surface conditionally...

I think that explicit error is much better because if you let tcomb handle it, the error message is rather cryptic and user has to have a look at actual implementation to understand what's wrong.

**Comment by gcanti** [comment]
> It's not good to change API surface conditionally

Good point. Let's keep the current implementation then

**Comment by danielkcz** [comment]
Well but current implementation is faulty obviously...By that comment I meant to keep `dispatch` there no matter number of actions.

Also I don't see why you don't agree on that error message. Do you really expect everyone to check to source code to find out what has happened? It doesn't even need to be intentional that you pass no actions there and suddenly you see cryptic message about some union which you are not using anywhere.

**Comment by gcanti** [comment]
Actually I agree with you for what concerns `dispatch`, it's a good observation. But, as you pointed out, it's an even better idea do not change the APIs conditionally, so I'll keep the current implementation. I find the message quite descriptive but perhaps because I'm used to. I'll try to add a better message, thanks for pointing out.

**Comment by danielkcz** [comment]
But this PR wasn't about changing `dispatch`, but to fix issue if there only a single action. You don't consider that an issue anymore?

**Pull request closed without merging**
